### ISSUE TITLE
Erlang OTP 22 is incorrectly identified as 11.0

### ISSUE THREAD

**Issue by mccw** [btc-ag/chef-rabbitmq-win#5]
The recipe is failing on the newest release of Erlang. The correct version as reported by the installed and the Erlang website is 10.4, not 11.0.

- install version latest of package Erlang OTP 22 (11.0)

* execute[Install RabbitMQ plugin rabbitmq_management] action run[2019-05-20T10:16:10-05:00] INFO: Processing execute[Install RabbitMQ plugin rabbitmq_management] action run (c:/chef/cache/cookbooks/rabbitmq-win/resources/plugin.rb line 5)

[execute] The system cannot find the path specified.

******************************
ERLANG_HOME not set correctly.
******************************

Please either set ERLANG_HOME to point to your Erlang installation or place the
RabbitMQ server distribution in the Erlang lib folder.

**Comment by claasd** [comment]
Hi @mccw 
Could you share your recipe / attributes file?

Thanks, Claas

**Comment by mccw** [comment]
Yessir,

This is the current recipe:

https://bitbucket.org/snippets/ScottMcCollough/eaXe7G

It looks like it's trying to set ERLANG_HOME to C:\Program Files\erl11.0 instead of C:\Program Files\erl10.4 and then failing when attempting to install the plugins.

**Comment by mccw** [comment]
I'm receiving this error while running updates on our linux rabbitmq clusters, so there may still be issues with the new versions of erlang and rabbit.

The repository 'https://dl.bintray.com/rabbitmq-erlang/debian bionic Release' no longer has a Release file.
